### ISSUE TITLE
[Feature Request] Include a Freedesktop .desktop (menu/launcher)

### ISSUE THREAD

**Issue by OdinVex** [desbma/gotify-desktop#13]
If you could include a ".desktop" file for use with Desktop Environments to ease starting and adding to automatic start (via pointing say, KDE's autostart to a .desktop) it might be a nice feature. Manually creating it works fine, though.

**Comment by desbma** [comment]
Yes I guess since this daemon is for desktop use, creating a Desktop file makes sense.

**Comment by desbma** [comment]
@OdinVex Can you please try the .desktop file from [`desktop-entry`](https://github.com/desbma/gotify-desktop/tree/desktop-entry/desktop) branch?
`desktop/gotify-desktop.desktop` should got in `/usr/share/applications/gotify-desktop.desktop`
`desktop/icon.png` should got in `/usr/share/icons/hicolor/96x96/apps/gotify-desktop.png`

**Comment by desbma** [comment]
I have added a "category" in the desktop file.

Copying the .desktop & icon file, updating the icon cache and such is typically the job of a distribution package. I'll update the Arch Linux AUR one since I maintain it, the best I can do for the other distros is add instructions in the README.

**Comment by desbma** [comment]
4df9b7d3ff6df8037516dd756681b65374074bf6 looks good to you?

**Comment by desbma** [comment]
I just stole the Gotify server favicon :blush: 
Gotify has SVGs [here](https://github.com/gotify/logo), but only of the main logo, which does not look great as a smallish icon.

**Comment by desbma** [comment]
There is clearly a generic Gotify logo, and another one designed for small icons, made to be more legible in small sizes, exactly our use case here.
I understand the benefits of using SVG instead of PNG, but in this case I don't think it makes sense to use the generic logo just for the sake of using SVG.

Anyway, this is released in 1.3.3 and the AUR package has been updated.

**Comment by desbma** [comment]
No it's not the same logo, they made a small one that is cropped, it's not just a raster version of the SVG, see https://github.com/gotify/logo#full-logo.

**Comment by desbma** [comment]
So you are using a tool to convert the small PNG logo to a SVG, in a fundamentally inaccurate way, so that your desktop environment can then raster it to an image of the same size?
That sounds complex and inefficient, and I would be very surprised if it results in better looking image, even when upscaling.

**Comment by desbma** [comment]
I'm impressed, this looks good indeed.

**Comment by desbma** [comment]
What is the tool you are using for the PNG -> SVG conversion?

**Comment by desbma** [comment]
SVG icon added in aac929d9a16331ed686792e3e303dc49ffd901bc and [AUR package updated](https://github.com/desbma/ArchLinuxPackages/commit/ac03a8dd00f87dc8fdcde9445183fa81ffa4e432).

**Comment by desbma** [comment]
Thanks, fixed for both.
I did not notice the missing `Icon=` line because my launcher (rofi) picks the icon anyway, I assume from the executable name.
